#!/usr/bin/bash 
#
#How to Install MongoDb and Mongosh on Linux (debian) officially

# Step 1: Update System Packages
sudo apt update

# Step 2: Install MongoDB Package 
sudo apt install mongodb -y

# 3: Start MongoDB Service
sudo service mongodb start

# Step 4: Verify MongoDB Status
sudo service mongodb status

# You should see output similar to the following, indicating that the service is active and running:
#● mongodb.service - An object/document-oriented database
#     Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: enabled)
#     Active: active (running) since [Timestamp]
#       Docs: man:mongod(1)
#   Main PID: [PID]
#      Tasks: [Task Count]
#     Memory: [Memory Usage]
#        CPU: [CPU Usage]
#     CGroup: /system.slice/mongodb.service
#             └─ [PID] /usr/bin/mongod --config /etc/mongod.conf


# Step 5: Enable the MongoDB Service - To make MongoDB start automatically upon power on or system boot
sudo systemctl enable mongodb

# Step 5: Connect to MongoDB
mongo
