#!/usr/bin/bash 
#
# Mongosh is a newer version but not supported since is not supported. It's NOT recommended to use any workaround in #Linux(debian) to install MongoDB, because it can lead to problems if you gonna use it in production. Below is the #workaround that worked for me:

#Download libssl1.1_1.1.1f-1ubuntu2_amd64.deb from official repository:
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb

#Install it:
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

#Proceed with the installation of MongoDB:
wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
sudo apt update
sudo apt install mongodb-org

#Start MongoDB service
sudo service mongod start

#You can now use Mongosh by styping mongosh on terminal
mongosh

#out is as shown below, some errors may show :

#Current Mongosh Log ID:	64d36a30cdac5aecaa190ad8
#Connecting to:		mongodb://127.0.0.1:27017/?#directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.3
#Using MongoDB:		6.0.8
##Using Mongosh:		1.10.3

#For mongosh info see: https://docs.mongodb.com/mongodb-shell/

#------
#   The server generated these startup warnings when booting
#   2023-08-09T13:04:31.302+03:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
#   2023-08-09T13:04:35.849+03:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
#   2023-08-09T13:04:35.849+03:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
 #  2023-08-09T13:04:35.850+03:00: vm.max_map_count is too low
#------

#test>
